version: '3.9'

x-customizable-image: &customizable_image
  # No usamos una imagen preconstruida, construimos localmente desde Dockerfiles
  build:
    context: .
    dockerfile: build/backend.Dockerfile

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: [*depends_on_configurator, *customizable_image]
  volumes:
    - /opt/erp/sites:/home/frappe/frappe-bench/sites

services:
  configurator:
    <<: *backend_defaults
    platform: linux/arm64
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: 9000
    depends_on: {}

  backend:
    build:
      context: .
      dockerfile: build/backend.Dockerfile
    platform: linux/arm64
    environment:
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: frappe
      DB_PASSWORD: frappe
      DB_NAME: frappe
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue

  frontend:
    build:
      context: .
      dockerfile: build/frontend.Dockerfile
    platform: linux/arm64
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket

  websocket:
    build:
      context: .
      dockerfile: build/socketio.Dockerfile
    platform: linux/arm64
    environment:
      REDIS_SOCKETIO: redis-socketio:6379
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites
    depends_on:
      - redis-socketio

  queue-short:
    <<: *backend_defaults
    platform: linux/arm64
    command: bench worker --queue short,default

  queue-long:
    <<: *backend_defaults
    platform: linux/arm64
    command: bench worker --queue long,default,short

  scheduler:
    <<: *backend_defaults
    platform: linux/arm64
    command: bench schedule

# Redis y MariaDB con versiones ARM64
  redis-cache:
    image: arm64v8/redis:6.2-alpine
    platform: linux/arm64
    volumes:
      - /opt/redis/cache:/data

  redis-queue:
    image: arm64v8/redis:6.2-alpine
    platform: linux/arm64
    volumes:
      - /opt/redis/queue:/data

  mariadb:
    image: arm64v8/mariadb:10.5
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe
      MYSQL_DATABASE: frappe
    volumes:
      - /opt/mariadb:/var/lib/mysql

volumes:
  sites:
