version: '3.9'

services:
  # Backend Service
  backend:
    image: alacorazza/frappe-backend-arm64:v14
    platform: linux/arm64
    environment:
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: frappe
      DB_PASSWORD: frappe
      DB_NAME: frappe
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  # Frontend Service
  frontend:
    image: alacorazza/frappe-frontend-arm64:v14
    platform: linux/arm64
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket

  # WebSocket Service
  websocket:
    image: alacorazza/frappe-socketio-arm64:v14
    platform: linux/arm64
    environment:
      REDIS_SOCKETIO: redis-socketio:6379
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites
    depends_on:
      - redis-socketio

  # Redis for Cache
  redis-cache:
    image: arm64v8/redis:6.2-alpine
    platform: linux/arm64
    volumes:
      - /opt/redis/cache:/data
    command: ["redis-server", "--maxmemory-policy", "allkeys-lru"]

  # Redis for Queue
  redis-queue:
    image: arm64v8/redis:6.2-alpine
    platform: linux/arm64
    volumes:
      - /opt/redis/queue:/data

  # Redis for WebSocket
  redis-socketio:
    image: arm64v8/redis:6.2-alpine
    platform: linux/arm64
    volumes:
      - /opt/redis/socketio:/data

  # MariaDB Service
  mariadb:
    image: arm64v8/mariadb:10.5
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe
      MYSQL_DATABASE: frappe
    volumes:
      - /opt/mariadb:/var/lib/mysql

volumes:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
  sites:
  mariadb-data:
