x-customizable-image: &customizable_image
  # Utiliza imágenes personalizadas para ARM64
  image: ${CUSTOM_IMAGE:-frappe/erpnext-arm64}:${CUSTOM_TAG:-v14}
  pull_policy: ${PULL_POLICY:-always}

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: [*depends_on_configurator, *customizable_image]
  volumes:
    - /opt/erp/sites:/home/frappe/frappe-bench/sites

services:
  configurator:
    <<: *backend_defaults
    platform: linux/arm64
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: 9000
    depends_on: {}

  backend:
    <<: *backend_defaults
    platform: linux/arm64

  frontend:
    <<: *customizable_image
    platform: linux/arm64
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$$host}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket

  websocket:
    <<: [*depends_on_configurator, *customizable_image]
    platform: linux/arm64
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - /opt/erp/sites:/home/frappe/frappe-bench/sites

  queue-short:
    <<: *backend_defaults
    platform: linux/arm64
    command: bench worker --queue short,default

  queue-long:
    <<: *backend_defaults
    platform: linux/arm64
    command: bench worker --queue long,default,short

  scheduler:
    <<: *backend_defaults
    platform: linux/arm64
    command: bench schedule

# Redis y MariaDB con versiones ARM64
  redis-cache:
    image: arm64v8/redis:6.2-alpine
    platform: linux/arm64
    volumes:
      - /opt/redis/cache:/data

  redis-queue:
    image: arm64v8/redis:6.2-alpine
    platform: linux/arm64
    volumes:
      - /opt/redis/queue:/data

  mariadb:
    image: arm64v8/mariadb:10.5
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe
      MYSQL_DATABASE: frappe
    volumes:
      - /opt/mariadb:/var/lib/mysql

volumes:
  sites:
